### ISSUE TITLE
eb-cli image

### ISSUE THREAD

**Issue by seromenho** [fstab/docker-aws-cli#2]
Hey!
It would be useful to have [Elastic Beanstalk Command Line Interface (EB CLI)](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3.html)
I have forked your aws-cli image and made the adjustments for eb-cli.
It's here: https://hub.docker.com/r/rseromenho/eb/ 

```Dockerfile
# DESC: Docker file to run EB CLI tools.
FROM gliderlabs/alpine:3.6
MAINTAINER Stuart Wong <cgs.wong@gmail.com>

ENV PAGER="more"

RUN apk --no-cache add \
      bash \
      curl \
      git \
      jq \
      groff \
      py-pip \
      python &&\
    pip install --upgrade \
      pip \
      awsebcli &&\
    mkdir ~/.aws

# Expose volume for adding credentials
VOLUME ["~/.aws"]

ENTRYPOINT ["/usr/bin/eb"]
CMD ["--version"]
```

**Comment by fstab** [comment]
Sounds good, I hope I can try it in the next couple of days...

**Comment by fstab** [comment]
I looked into your image. To me it seems it's intended as a replacement for the original `eb` command. Using `/usr/bin/eb` as the entry point makes most sense if the intended use is to define a shell alias like `alias eb='docker run --rm -t -i rseromenho/eb'` and thus provide an `eb` command without having to install it locally.

This looks like a good idea. You probably need to mount a persistent volume to store the `eb init` configuration, but apart from that it should be a useful image.

However, if this is your goal it makes sense to have separate images for aws-cli and for eb-cli. The aws-cli image cannot have `/usr/bin/eb` as an entry point. My personal taste for the aws-cli image is to keep `/bin/bash` as an entry point and run all `aws` command within a single container. That way you can run `aws configure` followed by other `aws` commands within the same container without the need for an external persistent volume.
