### ISSUE TITLE
include `zip` package for use with AWS Lambda

### ISSUE THREAD

**Issue by sappharx** [fstab/docker-aws-cli#4]
Lambda functions are (or at least can be) created and updated from the CLI using zip files, but this image doesn't include `zip`. This would be a useful convenience feature.

The `aws` user doesn't have privileges to run `apt-get install zip`. Also, `sudo` isn't available and I couldn't `su root` either.

I tried cloning and building locally with `zip` added, but I ran into the issue with locales, which is what led to PR #3 .

**Comment by fstab** [comment]
Added `apt-get install -y zip`.
